### ISSUE TITLE
Is this bot still functional? Auth issues

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [shaunburdick/slack-jirabot#9]
I believe this is due to the `jira` package being outdated. https://github.com/jira-node/node-jira-client looks like the new standard.

Before forking, I would like to know if by any chance you have already a functional version/branch which I can try, otherwise I'll be definitely forking your project and try to get it working with the other package

**Comment by shaunburdick** [comment]
It is still functional. I don't have a branch using the new library but you are welcome to contribute if you'd like. Looks like they have a NPM package to use too, https://www.npmjs.com/package/jira-client

I might have some time this week to port it over if you do not.

What's your auth issue? I took a quick glance at the new package and it doesn't look like it does much different on that end.

**Comment by shaunburdick** [comment]
welp, I found some time to port it now. I haven't tested it yet, I will do some testing tomorrow but let me know here if the new library works.

https://github.com/shaunburdick/slack-jirabot/tree/library-port

**Comment by Fire-Dragon-DoL** [comment]
@shaunburdick thanks for the fast response. I get auth error for user or password incorrect, but I'm sure they are right, I'll double check for sure (I checked manually in console with env variables). Well my plan to migrate to the other package was specifically to ensure JIRA integration is working.

The bot boots fine, but as soon as it face a message with a JIRA issue, it crashes on `auth`. I read in the `jira` package it's unmaintained and due to this the auth requests are failing.

I can definitely look into creating a pull request for you, I was planning to do that actually. No hurry ;)

**Comment by Fire-Dragon-DoL** [comment]
Oh that's lovely, you are already done, thanks! I'll be testing it right now

**Comment by Fire-Dragon-DoL** [comment]
I'll be performing additioanl tests, right now I'm getting the following error:

```
2016-03-22T01:51:06.572Z - error:   Got an error trying to find CARB-1201 StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/home/vagrant/slack/jira/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/vagrant/slack/jira/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/home/vagrant/slack/jira/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/vagrant/slack/jira/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/vagrant/slack/jira/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

**BUT!** The bot is not crashing anymore, which is really good. Since I get 401, I should believe I have an issue with login, even though I tested with two different users and they both can't login (and can in browser, one is system admin).

I'll perform more test tomorrow, it's really late here right now

**Comment by Fire-Dragon-DoL** [comment]
Performed extensive tests on the `jira-client` and the old `jira`, can't manage to connect. Probably it's our JIRA installation, I'll talk to them a bit. It's extremely weird since I can view JSON with a normal http request through the browser.

**Comment by Fire-Dragon-DoL** [comment]
OK I tested the new branch and it works great. Looks like I was having an issue with the username. That's lovely. Consider the pull request reviewed ;)

**Comment by shaunburdick** [comment]
Great! Glad to hear that it is working. I'll do a couple tests on my end and get this merged into master.

**Comment by Fire-Dragon-DoL** [comment]
@shaunburdick for what it's worth, it breaks with strictssl, not sure why

**Comment by shaunburdick** [comment]
I know for me, I have to turn strictSSL off as the instance is on a local LAN so they only have self signed certificates installed. strictSSL will not accept self signed certs.

**Comment by Fire-Dragon-DoL** [comment]
Well it's no big deal, was mainly to let you know, the important thing is that it works, the team is already loving it ;)

:+1:
